CREATE TABLE STATION 
(ID NUMBER PRIMARY KEY, 
CITY CHAR(20), 
STATE CHAR(2), 
LAT_N NUMBER, 
LONG_W NUMBER);

INSERT INTO STATION VALUES (13, 'Phoenix', 'AZ', 33, 112);
INSERT INTO STATION VALUES (44, 'Denver', 'CO', 40, 105);  
INSERT INTO STATION VALUES (66, 'Caribou', 'ME', 47, 68);

SELECT * FROM STATION;

SELECT * FROM STATION WHERE LAT_N > 39.7;

CREATE TABLE STATS 
(ID NUMBER REFERENCES STATION(ID), 
MONTH NUMBER CHECK (MONTH BETWEEN 1 AND 12), 
TEMP_F REAL CHECK (TEMP_F BETWEEN -80 AND 150), 
RAIN_I REAL CHECK (RAIN_I BETWEEN 0 AND 100), 
PRIMARY KEY (ID, MONTH));

INSERT INTO STATS VALUES (13, 1, 57.4, 0.31);
INSERT INTO STATS VALUES (13, 7, 91.7, 5.15);
INSERT INTO STATS VALUES (44, 1, 27.3, 0.18);
INSERT INTO STATS VALUES (44, 7, 74.8, 2.11);
INSERT INTO STATS VALUES (66, 1, 6.7, 2.10);
INSERT INTO STATS VALUES (66, 7, 65.8, 4.52);

SELECT ST.CITY, S.MONTH, S.TEMP_F, S.RAIN_I FROM STATION ST INNER JOIN STATS S ON ST.ID = S.ID;

SELECT ST.CITY, S.MONTH, S.RAIN_I, S.TEMP_F FROM STATION ST INNER JOIN STATS S ON ST.ID = S.ID 
ORDER BY MONTH, RAIN_I DESC;

SELECT ST.CITY, S.MONTH, ST.LAT_N, S.TEMP_F FROM STATION ST INNER JOIN STATS S ON ST.ID = S.ID 
WHERE S.MONTH = 7 ORDER BY S.TEMP_F;

SELECT ST.CITY, MAX(S.TEMP_F) AS MAX_TEMP_F, MIN(S.TEMP_F) AS MIN_TEMP_F, ROUND(AVG(S.RAIN_I),2) AS AVG_RAIN_I FROM STATS S 
INNER JOIN STATION ST ON S.ID = ST.ID GROUP BY ST.CITY;

SELECT ST.CITY, S.MONTH, ROUND(((S.TEMP_F - 32) * 5/9),2) AS TEMP_IN_CELCIUS,  
ROUND((S.RAIN_I * 2.54),2) AS RAINFALL_IN_CM FROM STATION ST INNER JOIN STATS S ON ST.ID = S.ID;

UPDATE STATS SET RAIN_I = RAIN_I + 0.01;
SELECT * FROM STATS;

UPDATE STATS SET RAIN_I = 74.9 
WHERE MONTH = 7 
AND ID = 44;
SELECT * FROM STATS;
